services:
  - type: web
    name: file-share
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_ENDPOINT
        sync: false
      - key: R2_PUBLIC_BASE_URL
        sync: false
